// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elugpijoxhmudnzykcvg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsdWdwaWpveGhtdWRuenlrY3ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTA1MjksImV4cCI6MjA3MzIyNjUyOX0.o1f9pSraittGDewddh3V3mj7cKooJYYxQuAENCX56fE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});